/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class firstJNI */

#ifndef _Included_firstJNI
#define _Included_firstJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     firstJNI
 * Method:    displayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_firstJNI_displayHelloWorld
  (JNIEnv *, jobject);

/*
 * Class:     firstJNI
 * Method:    displayOther
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_firstJNI_displayOther
  (JNIEnv *, jobject);

/*
 * Class:     firstJNI
 * Method:    getLine
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_firstJNI_getLine
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
