//firstJNI.java

class firstJNI
{
    public native void displayHelloWorld();
    public native void displayOther();
    private native String getLine(String prompt);

    static {
     System.loadLibrary("firstJNI");//This is firstJNI.DLL
     /*if generated by borland
     System.loadLibrary("firstjni");//This is firstjni.dll
     */
    }
    
     public static void main(String[] args) 
        {
    firstJNI JN=new firstJNI();
        JN.displayHelloWorld();
    JN.displayOther();
        
        String input = JN.getLine("Enter Some Thing "); 
    System.out.println("You Entered " + input); 

        }
}
